#'******************************************************************************
#' Description: Simulation to show that the problem of interpreting the UN model.
#'******************************************************************************
source("src/base.R")
source("src/vis/vis_base.R")
source("src/hlp/hlp_model_cost_functions.R")
source("src/hlp/hlp_spring_pheno_models.R")
source("src/hlp/hlp_fit_spm.R")

library(data.table)
library(lubridate)


# Use HF & HB data as an example
# HF
hf_pheno_dt <- fread(file.path(gdir, "Data/ARD/hf_grd_temperature_pheno.csv"))
hf_pheno_dt[, Date := as_date(Date)]

# HB
hb_pheno_dt <- fread(file.path(gdir, "Data/ARD/hb_grd_temperature_pheno.csv"))
hb_pheno_dt[, Date := as_date(Date)]

hb_hf_dt <- rbind(
    hf_pheno_dt[, .(siteID, Date,
        Tmean = Temp, Tmax = NA, Tmin = NA, SOS,
        PhenoYear
    )],
    hb_pheno_dt[, .(siteID, Date, Tmean, Tmax, Tmin, SOS, PhenoYear)]
)

# For now I only need one site.
# Use site `1B` as it has the most number of site-years.
site_li <- FormatDataForPhenoModel(site_dt)


# The result was generated by `simulate_interpretation.Rmd`
tot_CF_dt <- readRDS(file.path(gdir, "Pipeline", "un_sim_tot_CF_dt.Rds"))
numYr <- length(tot_CF_dt[iter == 0, C_tot])

# fig: UN model chilling and forcing uncertainty
{
    png(file.path("Output/Assets", "UN_sim_prob.png"), 
        res = 150, width = 1500, height = 600
    )
    par(mfrow = c(1, 2), mar = c(4, 4, 1, 1), cex.lab = 1.2)
    # forcing
    plot(NA,
        xlim = c(1, numYr), ylim = c(0, 70), mgp = c(2, 0.5, 0),
        xlab = "Simulated year Index", ylab = "Accumulated forcing", las = 1
    )
    null <- by(tot_CF_dt, tot_CF_dt$iter, function(i) {
        lines(1:numYr, i$F_tot, col = Transparent(color_frc, 0.3))
    })
    lines(tot_CF_dt[iter == 0, F_tot], type = "l", col = color_frc, lwd = 4)

    # chilling
    plot(NA,
        xlim = c(1, numYr), ylim = c(0, 400), mgp = c(2, 0.5, 0),
        xlab = "Simulated year Index", ylab = "Accumulated chilling", las = 1
    )
    null <- by(tot_CF_dt, tot_CF_dt$iter, function(i) {
        lines(1:numYr, i$C_tot, col = Transparent(color_chi, 0.3))
    })
    lines(tot_CF_dt[iter == 0, C_tot],
        type = "l",
        ylim = c(0, 60),
        col = color_chi,
        lwd = 4
    )
    
    dev.off()
}
